DjangoCv/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from resume import views #import my views
from django.urls import path



from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^resume/$', views.index, name='index'),
]
urlpatterns += [ #Add Django site authentication urls (for login, logout, password management)
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'cv/', include('resume.urls'))
]


if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#urlpatterns += [
#] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#urlpatterns += [
#] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from resume import views #import my views
from django.urls import path



from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^down/$', views.download, kwargs={'path':"~/Téléchargements"}, name='download'),
    url(r'^pdf2/$', views.GeneratePdf.as_view(), name='pdf'),
    #url(r'^pdf3/$', views.myviewpdf, name='pdf2'),
    url(r'^pdf/(?P<perso_id>[\d]+)/$', views.genereCvHtml2pdf, name='wkpdf'),
    url(r'^add/$',views.Resume_Forms.as_view(),name="step_forms"),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
### TODO <int:pk> can be a slug - https://chriskief.com/2012/12/29/django-generic-detailview-without-a-pk-or-slug/
urlpatterns += [
    path('overview/create/', views.OverviewCreate.as_view(), name='overview_create'),
    path('overview/<int:pk>/update/', views.OverviewUpdate.as_view(), name='overview_update'),
    path('overview/<int:pk>/delete/', views.OverviewDelete.as_view(), name='overview_delete'),
    path('personalinfo/create/', views.PersonalInfoCreate.as_view(), name='personalinfo_create'),
    path('personalinfo/<int:pk>/update/', views.PersonalInfoUpdate.as_view(), name='personalinfo_update'),
    path('personalinfo/<int:pk>/delete/', views.PersonalInfoDelete.as_view(), name='personalinfo_delete'),
    path('education/create/', views.EducationCreate.as_view(), name='education_create'),
    path('education/<int:pk>/update/', views.EducationUpdate.as_view(), name='education_update'),
    path('education/<int:pk>/delete/', views.EducationDelete.as_view(), name='education_delete'),
]
'''

resume/models.py
from django.db import models
import time
from datetime import date
from django.contrib.auth.models import User, Group, Permission

def showall(klass):
    for object in klass.objects.all():
        print('----- ' + klass._meta.model_name)
        for field in object._meta.get_fields():
            value = getattr(object, field.name, None)
            print(field.name, value)


class Language(models.Model):
    name = models.CharField(max_length=20,blank=False)

    class Meta:
        verbose_name_plural = "10. Languages"
        ordering = ['name']

    def __unicode__(self):
        return self.name
    def __str__(self):
        return self.name


class PersonalInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255)
    suffix = models.CharField(max_length=255, help_text="e.g. PhD", blank=True, null=True)
    locality = models.CharField(max_length=255, help_text="e.g. city such as Boston", blank=True, null=True)
    region = models.CharField(max_length=255, help_text="e.g. MA or Italy", blank=True, null=True)
    title = models.CharField(max_length=255, help_text="e.g. Developer", blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    linkedin = models.URLField(blank=True, null=True)
    facebook = models.URLField(blank=True, null=True)
    github = models.URLField(blank=True, null=True)
    site = models.URLField(blank=True, null=True)
    twittername = models.CharField(max_length=100, blank=True, null=True)
    image = models.ImageField(upload_to='static/resume/img/',blank=True, null=True)
    cv_pdf = models.FileField(upload_to='static/resume/img/', blank=True, null=True, help_text='Downloadable resume file')

    language = models.ManyToManyField(Language, through='MesLanguages', related_name="mes_language",
                                       through_fields=('personal', 'language'))
    programming_language = models.ManyToManyField('ProgrammingLanguage', through='MesLanguageProgrammation', related_name="mes_programming_language",
                                       through_fields=('personal', 'programming_language'))
    phone = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        verbose_name_plural = "01. Personal Info"

    def full_name(self):
        return " ".join([self.first_name, self.last_name])

    def githubname(self):
        print('git='+str(self.github))
        if self.github != '':
            return self.github.rsplit('/',maxsplit=1)[1]
        else:
            return None
    def __unicode__(self):
        return self.full_name()
    def __str__(self):
        return self.full_name()


class Overview(models.Model):
    personal = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)
    text = models.TextField()
    class Meta:
        verbose_name_plural = "02. Overview"
    def __unicode__(self):
        return self.text[0:40] + '...'
    def __str__(self):
        return self.text[0:40] + '...'

class Education(models.Model):
    personal = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    name2 = models.CharField(max_length=250, blank=True)
    location = models.CharField(max_length=250)
    location2 = models.CharField(max_length=250, blank=True)
    schoolurl = models.URLField('School URL', blank=True)
    schoolurl2   = models.URLField('School URL2', blank=True)
    start_date  = models.DateField(default=date.today)
    end_date    = models.DateField(default=date.today)
    degree = models.TextField(blank=True)
    description = models.TextField(blank=True)
    #is_current = models.BooleanField(default=True)
    class Meta:
        verbose_name_plural = "03. Education"
        ordering = ['-end_date','id']
    def edu_date_range(self):
        return ' - '.join(['(', self.formatted_start_date(),
                            self.formatted_end_date(), ')'])
    def full_start_date(self):
        return self.start_date.strftime("%Y-%m-%d")
    def full_end_date(self):
        if (self.end_date == None):
            return time.strftime("%Y-%m-%d", time.localtime())
        else:
            return self.end_date.strftime("%Y-%m-%d")
    def formatted_start_date(self):
        return self.start_date.strftime("%b %Y")
    def formatted_end_date(self):
        if (self.end_date == None):
            return "Present"
        else:
            return self.end_date.strftime("%b %Y")
    def __unicode__(self):
        return ' '.join([self.name, self.edu_date_range()])
    def __str__(self):
        return self.name

class Job(models.Model):
    personal = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)
    company = models.CharField(max_length=250)
    companyurl = models.URLField('Company URL')
    location = models.CharField(max_length=250)
    title = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    start_date  = models.DateField(default=date.today)
    end_date    = models.DateField(default=date.today)
    is_current = models.BooleanField(default=False)
    is_public = models.BooleanField(default=True)
    company_image = models.CharField(max_length=250, blank=True,
        help_text='path to company image, local or otherwise')
    class Meta:
        db_table = 'jobs'
        verbose_name_plural = "04. Jobs"
        ordering = ['-end_date','id']
    def job_date_range(self):
        return ' - '.join(['(', self.formatted_start_date(),
            self.formatted_end_date(), ')'])
    def full_start_date(self):
        if self.start_date is None:
            return None
        return self.start_date.strftime("%Y-%m-%d")
    def full_end_date(self):
        if (self.is_current is True):
            return time.strftime("%Y-%m-%d", time.localtime())
        else:
            return self.end_date.strftime("%Y-%m-%d")
    def formatted_start_date(self):
        if self.start_date is None:
            return None
        return self.start_date.strftime("%b %Y")
    def formatted_end_date(self):
        if self.is_current == True or self.end_date is None:
            return "Present"
        else:
            return self.end_date.strftime("%b %Y")
    def __unicode__(self):
        return ' '.join([self.company, self.job_date_range()])
    def __str__(self):
        return self.company

class JobAccomplishment(models.Model):
    personal = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)
    description = models.TextField()
    job = models.ForeignKey('Job',on_delete=models.CASCADE)
    order = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = "05. Job Accomplishments"
        db_table = 'jobaccomplishment'
        ordering = ['order', 'id']

    def __unicode__(self):
        return ' - '.join([self.job.company, self.description[0:50]+'...'])

    def __str__(self):
        return self.description[0:10]+'...'

class Skillset(models.Model):
    name = models.TextField()

    class Meta:
        verbose_name_plural = "06. Skillsets"
        ordering = ['id']
    def __unicode__(self):
        return self.name
    def __str__(self):
        return self.name

class Skill(models.Model):
    personal = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)
    text =  models.TextField()
    order = models.IntegerField(default=1)
    skillurl = models.URLField('Skill URL', null=True, blank=True)
    skillset = models.ForeignKey('Skillset',on_delete=models.CASCADE, related_name="mes_skills")

    class Meta:
        verbose_name_plural = "07. Skills"
        ordering = ['order','id']
    def __unicode__(self):
        return ' - '.join([self.skillset.name, self.text])
    def __str__(self):
        return self.text

class ProgrammingArea(models.Model):
    name = models.CharField(max_length=250)
    order = models.IntegerField(default=1)
    class Meta:
        verbose_name_plural = "08. Programming areas"
        ordering = ['order','name']
    def __str__(self):
        return self.name

class ProgrammingLanguage(models.Model):
    name = models.CharField(max_length=250)
    programmingarea = models.ForeignKey('ProgrammingArea',on_delete=models.CASCADE)
    description = models.CharField(max_length=50, blank=True)

    class Meta:
        verbose_name_plural = "09. Programming languages"
        db_table = 'programminglanguage'
        ordering = ['name', 'id']

    def __unicode__(self):
        return self.name
    def __str__(self):
        return self.name


class MesLanguageProgrammation(models.Model):
    programming_language  = models.ForeignKey(ProgrammingLanguage, on_delete=models.CASCADE)
    personal  = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)
    NIH_proficiency_scale = (
        (5, 'Expert'),
        (4, 'Advanced'),
        (3, 'Intermediate'),
        (2, 'Novice'),
        (1, 'Fundamental Awareness')
        )
    level = models.IntegerField(help_text='Choice between 1 and 5', choices=NIH_proficiency_scale, default=1)

    order = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = "11. Mes languages Programmation"
        ordering = ['order', 'id']

    def __unicode__(self):
        return self.programming_language.name
    def __str__(self):
        return self.programming_language.name


class MesLanguages(models.Model):
    language  = models.ForeignKey(Language, on_delete=models.CASCADE)
    personal  = models.ForeignKey(PersonalInfo, on_delete=models.CASCADE)

    order = models.IntegerField(default=1)
    ILR_scale = (
        (5, 'Native'),
        (4, 'Full professional proficiency'),
        (3, 'Professional working proficiency'),
        (2, 'Limited professional proficiency'),
        (1, 'Elementary professional proficiency')
        )

resume/templates/resume/cv_form_1.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}

<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
  {{ wizard.management_form }}
  {% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
      {{ form }}
    {% endfor %}
  {% else %}
    {{ wizard.form }}
  {% endif %}
  </table>
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
  {% endif %}
  <input class="btn btn-success btn-lg pull-left" type="submit" value="{% trans "submit" %}"/>
</form>
{% endblock %}

resume/templates/resume/cv_form_5.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<h3> Compètences informatique </h3>
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
  {{ wizard.management_form }}
  {% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
      {{ form }}
    {% endfor %}
  {% else %}
    {{ wizard.form }}
  {% endif %}
  </table>
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
  <div class="form-control">
    <input type="submit" class="next-btn" value="{% trans "Next" %}"/>
  </div>
  {% endif %}
</form>
{% endblock %}

resume/templates/resume/formpart_5.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title_block %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link href="{%  static "CSS/formpart.css" %}" rel="stylesheet">
<style>

.left-4{
    width:35%;
    border-right:2px solid purple;
    margin:20px;
}
.right-4{
    margin:20px;
}
#lang_id{
    width: 195px;
}
#val_id {
    width: 120px;
}
.form-control{
    height:50px;
}
.btn-delete{
    background-image: url("{% static "images/remove.png" %}");
    margin:5px;
    height:48px;
    cursor:pointer;
    box-shadow:transparent;
    outline:none;
    border:0.1em solid white;
    font-weight:300;
    font-family: 'Bebas Neue', cursive;
    background-repeat: no-repeat;
    width:48px;
    padding:0px;
    background-position:50% 50%;

}
.btn-delete:hover{
    border: 0.1em solid red;
}
.col{
    flex-grow:0;
}
.lan{
    border:1px solid;
    padding: 5px;
    margin:5px ;
    width:auto ;
}
</style>
{% endblock %}
{% block body_block %}


<div class="whole_page">
    <div class="center_page_1">
        <div class="left-4">
            <h1>ADD SKILL</h1>
            <p>Step {{wizard.steps.step1}} of {{ wizard.steps.count }}</p>
            <div class="lan">
                <h6>Rate your skill level between 1 to 5</h6>
            </div>
        </div>
        <div class="right-4">
          <form method="post">{% csrf_token %}
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
       <div class="form-row form-row-4">
           <div class="col" >{{ form.skill_set }}</div>
           <div class="col" >{{ form.skill_level }}</div>
           <button class="btn-delete"></button>
       </div>
        <button class="add-class-4">+</button>
    {% endfor %}

{% else %}
    {{ wizard.form }}
{% endif %}
{% if wizard.steps.prev %}
<button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}" class="step-btn">{% trans "Prev" %}</button>
{% endif %}
          <input type="submit" class="next-btn" value="{% trans "Next" %}"/>
          </form>
        </div></div></div>
    <script src="{% static "JS/formscript_5.js" %}"></script>
{% endblock %}

resume/templates/resume/html_cv.html
{% extends "base_html.html" %}
{% load static %}


{% block sideNav %}
    <div class="row-fluid">
       <h3>Resume </h3>
       <img class="img-fluid img-profile rounded-circle mx-auto mb-2"
       src="pinfo.image.url" alt="Pas de photo pinfo.image.url">
       <h1> {{ pinfo.first_name }} {{ pinfo.middle_name }} </h1>

           <div class="">
             <h1 class="mb-0">{{ pinfo.first_name }} {{ pinfo.middle_name }}
               {% spaceless %}
               <span class="primary">{{ pinfo.last_name}}</span>
               {% if pinfo.suffix %}
               <span style="text-transform: none;">, {{ pinfo.suffix}}</span>
               {% endif %}
               {% endspaceless %}
             </h1>
             <div class="subheading mb-5">{{pinfo.title}}
               {% if pinfo.email %}
               {% if overview.text %}
               <a href="mailto:{{ pinfo.email }}">{{ pinfo.email }}</a>
               {% endif %}
               {% endif %}
             </div>
             {% with overview|first as overview %}
             <p class="mb-5">{{ overview.text|safe }}</p>
             {% endwith %}

             <ul class="list-inline list-social-icons mb-0">
               {% if pinfo.email %}
               <li class="list-inline-item">
                 <a href="mailto:{{pinfo.email}}" target="_blank" title="Send me an email">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}
               {% if pinfo.site %}
               <li class="list-inline-item" target="_blank">
                 <a href="{{pinfo.site}}" target="_blank" title="My site at: {{pinfo.site}}">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-globe fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}
               {% if pinfo.facebook %}
               <li class="list-inline-item">
                 <a href="{{pinfo.facebook}}" target="_blank" title="Go to my facebook page">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}
               {% if pinfo.twitter %}
               <li class="list-inline-item">
                 <a href="{{pinfo.twitter}}" target="_blank" title="Go to my twitter account">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}
               {% if pinfo.linkedin %}
               <li class="list-inline-item">
                 <a href="{{pinfo.linkedin}}" target="_blank" title="Go to my linkedin account">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}
               {% if pinfo.github %}
               <li class="list-inline-item">
                 <a href="{{pinfo.github}}" target="_blank" title="Go to my github account">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}

               {% if pinfo.cv_pdf %}
               <li class="list-inline-item">
                 <a href="{{ pinfo.cv_pdf.url }}" target="_blank" title="Download CV in PDF">
                   <span class="fa-stack fa-lg">
                     <i class="fa fa-circle fa-stack-2x"></i>
                     <i class="fa fa-file-pdf-o fa-stack-1x fa-inverse"></i>
                   </span>
                 </a>
               </li>
               {% endif %}
             </ul>
           </div>
    </div>
{% endblock %}

{% block content %}

  {% with personal_info|first as pinfo %}


    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
      <div class="my-auto">
        <h2 class="mb-5">Experience</h2>
        {% for job in job_list %}
        <h4 class="mb-0">{{ job.title|capfirst }}</h4>
        <div class="resume-item d-flex flex-column flex-md-row mb-5">
          <div class="resume-content mr-auto">
            <div class="subheading mb-3">
              {% if job.companyurl %}
              <a target="_blank" href="{{ job.companyurl }}">{{ job.company }}</a>
              {% else %}
              <a target="_blank" href="">{{ job.company }}</a>
              {% endif %}
            </div>
            {% autoescape off %}
            <p>{{ job.description }}</p>
            <div class="resume-date text-md-right">
              <div class="subheading mb-3 text-primary">{{ job.formatted_start_date }} - {{ job.formatted_end_date }}
                <p>{{ job.location|safe }}</p>
              </div>
            </div>

            <ul class="fa-ul mb-0">
              {% for acc in job.jobaccomplishment_set.all %}
              <li>
                <i class="fa-li fa fa-check"></i>
                {{ acc.description }}
              </li>
              {% endfor %}
            </ul>
            {% endautoescape %}
          </div>

        </div>
        {% endfor %}

      </div>
    </section>
    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
      <div class="my-auto">
        <h2 class="mb-5">Education</h2>
        {% for edu in education %}
          <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h4 class="mb-0">{{ edu.name|safe }}</h4>
              <div class="subheading mb-3">
                <h4 class="mb-0">{{ edu.degree }}</h4>
              </div>
              <p>
                {% if edu.schoolurl %}
                <a href="{{ edu.schoolurl }}" target="_blank">{{ edu.name|safe }}</a>
                {% endif %}
              </p>
              <p>{{ edu.description|safe }}</p>
            </div>
            <div class="resume-date text-md-right mb-0">
              <div class="subheading mb-3 text-primary">{{ edu.formatted_start_date }} - {{ edu.formatted_end_date }}</div>
              <p>{{ edu.location|safe }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>

    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">
      <div class="my-auto">
        <h2 class="mb-5">Skills</h2>
        <div class="subheading mb-3">
          <h3 class="mb-0">Programming Languages &amp; Tools</h3>
        </div>
        <ul>
          {% for parea in progarea %}
          <li>
            <p>
              <strong>{{ parea.name }}</strong>:
              {% for prog in parea.programminglanguage_set.all %}
              <span title={{prog.description}}>{{ prog.name }}</span>{%if not forloop.last%},{%endif%}
              {% endfor %}
            </p>
          </li>
          {% endfor %}
        </ul>
        <br>
        {% for sks in skillset %}
        <div class="subheading mb-3">
          <h3 class="mb-0">{{sks.name}}</h3>
        </div>
        <ul>
          {% for sk in sks.skill_set.all %}
          <li>
            <p>
            {{ sk.text }}
            {{ sk.skillurl }}
            </p>
          </li>
          {% endfor %}
        </ul>
        <br>
        {% endfor %}
        <div class="subheading mb-3">
          <h3 class="mb-0">Languages</h3>
        </div>
        <ul>
          {% for lan in language|dictsortreversed:"level" %}
          <li>
            <p>
            <strong>{{ lan.language }}</strong>: {{ lan.get_level_display }}
              {% if lan.addendum  %}
                {{ lan.addendum }}
              {% endif %}
            </p>
          </li>
          {% endfor %}
        </ul>
      </div>
    </section>

    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="achievements">
      <div class="my-auto">
        <h2 class="mb-5">Projects</h2>
        {% for prtype in projtype %}
        <div class="subheading mb-3">
            <h3 class="mb-0">{{ prtype.name }}</h3>
        </div>
        <ul class="achievements">
          {% for proj in project %}
          <ul class="fa-ul mb-0">
            <li>
              <i class="fa-li fa fa-check"></i>
              {% if proj.name %}
              <a href="{{ proj.link}}" target="_block">{{ proj.name }}</a>:
              {%endif%}
              {{ proj.short_description|safe }}
            </li>
          </ul>
          {% endfor %}
        </ul>
        <br>
        {% endfor %}

        <div class="container mx-0 px-0 my-3">
          <!--From https://codepen.io/thepeted/pen/ojvjbL with modal https://www.w3schools.com/howto/howto_css_modal_images.asp-->
          <div class="row">
            {% for proj in project %}
            {% if proj.image %}
            <div class="col-sm-4 col-md-3">
              <div id="{{ proj.name }}" class="thumb" alt="{{ proj.name }}" title="{{ proj.long_description }}"
                   onclick="openModal(this,event);" style="background-image: url({{ proj.image.url }});">

                <span class="fa-stack fa-lg launcher" s>
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-external-link fa-stack-1x fa-inverse"></i>
                </span>

                <div class="modal">
                    <span class="close">&times;</span>
                    <img class="modal-content">
                    <div class="caption"></div>
                    <a href="{{ proj.link }}">Go to</a>
                  </div>
              </div>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>

      </div>
    </section>

    <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="other">
      <div class="my-auto">
        <h2 class="mb-5">Other</h2>
        <div class="subheading mb-3">
          <h3 class="mb-0">Other Achievements</h3>
        </div>
        <ul class="achievements">
          {% for ach in achievement %}
          <ul class="fa-ul mb-0">
            <li>
              <i class="fa-li fa fa-check"></i>
              {% if ach.title %}
                {% if ach.url %}
                  <a href="{{ ach.url }}" target="_block">{{ ach.title }}</a>:
                {% elif ach.achievement_pdf %}
                  <a href="{{ ach.achievement_pdf.url }}" target="_block">{{ ach.title }}</a>:
                {%endif%}
              {%endif%}
              {{ ach.description|capfirst|safe }}
            </li>
          </ul>
          {% endfor %}
        </ul>
        <br>

        {% if publication %}
        <div class="subheading mb-3">
          <h3 class="mb-0">Publications</h3>
        </div>
        <ul class="achievements">
          {% for pub in publication %}
          <ul class="fa-ul mb-0">
            <li >
              <i class="fa-li fa fa-check" style="display:block;"></i>
              {{ pub.formatted_authors|safe }} {{ pub.title }}
                <span class="italic">{{ pub.journal }}</span>, {{ pub.year }}
                {% if pub.journalpages %}
                    {{ pub.year }}, {{ pub.journalpages }}.
                {% else %}
                    {{ pub.year }}.
                {% endif %}
              <a   target="_blank" href="{{ pub.link }}">Link</a>
            </li>
          </ul>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
    </section>

  {% endwith %}
{% endblock %}